FROM tomcat:7.0

# Download the sample WAR file directly into the webapps directory
ADD https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war /usr/local/tomcat/webapps/

# Expose port 8080
EXPOSE 8080
